/*   Messages used by the USBCAN library.
/*
/*   Messages represented by status codes.
/*
msg err1
  lan english -def
    USBCAN device "%p1s" is already in use.
msg err2
  lan english -def
    USBCAN device "%p1s" not found.
msg err3
  lan english -def
    All USBCAN devices are already in use.
msg err4
  lan english -def
    No USBCAN device found.
msg err5
  lan english -def
    Initial communication with the CAN device was not completed within the
    timeout. This probably indicates a communications error or device
    fault.
msg err6
  lan english -def
    Received unexpected response opcode %p1i from the device.
